version: '3.8'

# see 'docker/app/serve.sh' for software versions used in the app container
services:
  ual_gob_app:
    image: ual-goblight:latest
    container_name: gob-test
    user: gob
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8983:8983"
    env_file:
      - .env
    environment:
      - SOLR_JETTY_HOST=0.0.0.0
      - ZK_HOST=zoo1:2181
      - SOLR_URL=http://solr:SolrRocks@0.0.0.0:8983/solr/blacklight-core/
      - SOLR_VER=9.1.1
      - USER_UID
      - USER_GID
    # volumes:
    #   - geo_data:/geoblacklight/app
    networks:
      - solr
    depends_on:
      - zoo1
    # entrypoint: [ "/geoblacklight/serve.sh" ]
    tty: true

  solr2:
    image: "solr:${SOLR_VER}"
    container_name: solr2
    ports:
      - 8982:8983
    environment:
      - ZK_HOST=zoo1:2181
    volumes:
      - solr2_data:/opt/persist
    networks:
      - solr
    depends_on:
      - zoo1

  zoo1:
    image: "zookeeper:${ZOOKEEPER_VER}"
    container_name: zoo1
    restart: unless-stopped
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - zoo1_data:/opt/persist
    networks:
      - solr

networks:
  solr:

volumes:
  # geo_data:
  solr2_data:
  zoo1_data: