version: '3.8'

services:
  ual_gob_app:
    image: ual-goblight:latest
    container_name: gob-test
    user: gob
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:8983:8983"
    environment:
      - "USER_UID=${USER_UID:-1000}"
      - "USER_GID=${USER_GID:-1000}"
    env_file:
      - .env
    volumes:
      - ./ual_gob:/geoblacklight
      - ./docker:/home/gob/docker
    networks:
      - solr
    depends_on:
      - zoo1
    tty: true

  zoo1:
    image: "zookeeper:${ZK_VERSION:-latest}"
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - zoo1_data:/data
    networks:
      - solr

networks:
  solr:

volumes:
  zoo1_data:
