version: '3.8'

services:
  ual_gob_app:
    image: ual-goblight:latest
    container_name: gob-app
    user: gob
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - "USER_UID=${USER_UID:-1000}"
      - "USER_GID=${USER_GID:-1000}"
      - ENGINE_CART_RAILS_OPTIONS=--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test --skip-solr
    env_file:
      - .env
    volumes:
      - ./ual_gob:/geoblacklight
      - ./docker/app:/home/gob/docker
    depends_on:
      - ual_zookeeper
    networks:
      - solr
    tty: true

  ual_solr:
    image: ual-solr:latest
    container_name: solr1
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - solr1_data:/var/solr
      - ./docker/solr/cloud-secure.sh:/home/solr/docker/cloud-secure.sh
    depends_on:
      - ual_zookeeper
    networks:
      - solr
    command: bash -c "/home/solr/docker/cloud-secure.sh"

  ual_zookeeper:
    image: "zookeeper:${ZK_VERSION:-latest}"
    container_name: zoo1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=mntr, conf, ruok
      - ZOO_CFG_EXTRA="metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - zoo1_data:/data
    networks:
      - solr

networks:
  solr:

volumes:
  solr1_data:
  zoo1_data:
