version: '3.8'

services:
  ual_gob_app:
    image: ual-goblight:latest
    container_name: gob-app
    user: gob
    environment:
      - RAILS_ENV=development
    env_file:
      - .env
    volumes:
      - ./app:/geoblacklight/app
      - ./docker/app:/home/gob/docker
    depends_on:
      - ual_zookeeper
    networks:
      - traefik_default
    tty: true
    labels:
      - "traefik.http.routers.gob.rule=Host(`gob-test.library.arizona.edu`)"
      - "traefik.http.routers.gob.entrypoints=web-secure"
      - "traefik.http.routers.gob.tls=true"
      - "traefik.http.routers.gob.service=gob"
      - "traefik.http.routers.gob.middlewares=auth"
      - "traefik.http.routers.gob.tls.certresolver=incommon"
      - "traefik.http.services.gob.loadbalancer.server.port=3000"
      - "traefik.http.services.gob.loadbalancer.server.scheme=http"

  ual_solr:
    image: ual-solr:latest
    container_name: solr1
    volumes:
      - solr1_data:/var/solr
      - ./docker/solr/cloud-secure.sh:/home/solr/docker/cloud-secure.sh
      - ./app/solr/conf:/blacklight-core
      - /home/odeak/uaz/files/solr-data/data/UAL_GeospatialRecords:/UAL_GeospatialRecords
    depends_on:
      - ual_zookeeper
    networks:
      - traefik_default
    command: bash -c "/home/solr/docker/cloud-secure.sh"
    labels:
      - "traefik.http.routers.solr.rule=Host(`solr-test.library.arizona.edu`)"
      - "traefik.http.routers.solr.entrypoints=web-secure"
      - "traefik.http.routers.solr.tls=true"
      - "traefik.http.routers.solr.service=solr"
      - "traefik.http.routers.solr.tls.certresolver=incommon"
      - "traefik.http.services.solr.loadbalancer.server.port=8983"
      - "traefik.http.services.solr.loadbalancer.server.scheme=http"

  ual_zookeeper:
    image: "zookeeper:${ZK_VERSION:-latest}"
    container_name: zoo1
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888;2181
      - ZOO_4LW_COMMANDS_WHITELIST=mntr, conf, ruok
      - ZOO_CFG_EXTRA="metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - zoo1_data:/data
    networks:
      - traefik_default
    labels:
      - "traefik.http.routers.zoo.rule=Host(`zoo-test.library.arizona.edu`)"
      - "traefik.http.routers.zoo.entrypoints=web-secure"
      - "traefik.http.routers.zoo.tls=true"
      - "traefik.http.routers.zoo.service=zoo"
      - "traefik.http.routers.zoo.middlewares=auth"
      - "traefik.http.routers.zoo.tls.certresolver=incommon"
      - "traefik.http.services.zoo.loadbalancer.server.port=2181"
      - "traefik.http.services.zoo.loadbalancer.server.scheme=http"

networks:
  traefik_default:
    external: true

volumes:
  solr1_data:
  zoo1_data:
