version: '3.7'

services:
  app:
    image: ual-goblight:latest
    container_name: gob-test
    ports:
     - "127.0.0.1:3000:3000"
     - "127.0.0.1:8983:8983"
    env_file:
      - .env
    volumes:
      - ./app/:/geoblacklight
      - ./docker/:/home/geoblacklight/docker
    entrypoint: sh -c "/home/geoblacklight/docker/app/serve.sh"
