services:
  geoserver:
    container_name: geo1
    image: docker.osgeo.org/geoserver:2.25.x
    networks:
      - ual-gob
    ports:
      - 80:8080
    volumes:
      - ./data:/opt/geoserver_data/
    environment:
      - SKIP_DEMO_DATA=true

networks:
  ual-gob:
