services:
  geoserver:
    container_name: geo1
    image: docker.osgeo.org/geoserver:2.25.x
    networks:
      - ual-gob
    ports:
      - "8083:8080"
    volumes:
      - ./docker/geoserver/data:/opt/geoserver_data/
    environment:
      - SKIP_DEMO_DATA=true
    labels:
      - "traefik.http.routers.geoserver.entrypoints=gob-goser"
      - "traefik.http.routers.geoserver.rule=Host(`gobapp.localhost`)"
      - "traefik.enable=true"

networks:
  ual-gob:
    external: true
